export const predictions = {
    ordinary: ["Idleness is the Devil's plaything. It doesn't matter how fast you move, brother. The main thing is don't stop!",
                "Don't retreat, don't give up! The whole world will be against you but you are right, be inspired by this", 
                "Do not live in a swamp, routine. Live positively",
                "Bide your time, for success is near.",
                "Don't be afraid to take a stand...",
                "Listen to everyone. Ideas come from everywhere.",
                "The best prediction of future is the past",
                "Error: Fortune not found. You can install it by typing: sudo apt-get install fortune-mode",
                "Do it now! Today will be yesterday tomorrow!",
                "Change comes with embracing the future, not fighting your past.",
                "Big journeys begin with a single step.",
                "One that would have the fruit must climb the tree.",
                "Your road to glory will be rocky but fulfilling.",
                "Well done is better than well said.",
                "The early bird gets the worm, but the second mouse gets the cheese.",
                "A foolish man listens to his heart. A wise man listens to cookies."],
    love: ["A beautiful, smart, and loving person will be coming into your life.",
            "You will be rewarded for being a good listener",
            "It's better to be alone sometimes.",
            "You are in good hands this evening.",
            "Embrace this love relationship you have!",
            "Follow what calls you.",
            "Enter unknown territory.",
            "Friendship is a special kind of love.",
            "Always tell someone how you feel about them, you will feel much better when they know. hah...",
            "Hug your loved ones today.",
            "Love is like the wind, you can't see it, but you can feel it.",
            "The greatest thing you'll every learn, is just to love and be loved in return.",
            "Learn from your mistakes. Try not to make them again.",
            "The hardest thing to do is watch the one you love, love someone else.",
            "To love is to forgive.",
            "Your soul mate will not strictly judge you for your misdeeds."],
    money: ["A gambler not only will lose what he has, but also will lose what he doesn't have.",
            "The first man gets the oyster, the second man gets the shell.",
            "You paid ETH for cookies. Seriously???",
            "Maybe it's time to HODL BTC now?",
            "Winter is a great time to prepare for summer",
            "Summer is coming. Be ready",
            "This week, avoid any questionable transactions with money, otherwise you risk losing all your investments.",
            "Your main activity will bring you a stable income. You will be in high spirits, your success will be proud of your loved ones",
            "You need to devote more time to issues of property and housing. If you do not have your own home yet, then it's time to buy an apartment.",
            "There is a chance to make a profit from trading, financial and exchange operations.",
            "You can plan large investments and expect tangible returns from your projects",
            "If you have been with your organization for a long time, you can expect a salary increase. You have managed to prove yourself in the workplace on a good side, you are a highly qualified specialist and an original person.",
            "Do not spare money for your loved ones. Perhaps they will be more important to them today than to you.",
            "Don't spend more than you earn. Try to manage your money wisely.",
            "If you still do not know how to get additional income and improve your financial condition, it's time to take up this issue."]
}